apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-ui
  template:
    metadata:
      labels:
        app: dog-ui
    spec:
      containers:
      - name: dog-ui-pod
        image: docker.io/mtmazurik/devopsgenie-ui:latest
        imagePullPolicy: Always
        ports:
        - name: dog-ui-port
          containerPort: 80

    

